# This file for redirecting the requesting from nginx to the application
server {
    # 1. البورت اللي Nginx هيسمع عليه جوه الكنترينر
    listen 80;

    # 2. الملفات الافتراضية اللي هيدور عليها
    index index.php index.html;

    server_name localhost;

    # 3. مسار تسجيل الأخطاء والزيارات
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

    # 4. الـ Root Document (مهم جداً في لارافل!)
    root /var/www/public;

    # 5. توجيه الطلبات (السر بتاع Laravel Routing)
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # 6. تمرير ملفات الـ PHP لكنترينر الـ App
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;

        # السطر السحري: بنكلم خدمة الـ app على بورت 9000
        fastcgi_pass app:9000;

        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}

